#!/bin/zsh
# Adds this script dirs bins to your bash
# Get the full path of the current directory
DIR="/Users/zacharyrowden/Desktop/SCRIPT/bash"

# Check if the directory is already in the PATH
if ! grep -q "$DIR" ~/.zshrc; then
    # Add the directory to the PATH
    echo "export PATH=\"$DIR:\$PATH\"" >> ~/.zshrc
    echo "Directory $DIR added to PATH in ~/.zshrc"

    # Apply the changes
    source ~/.zshrc
else
    echo "Directory $DIR is already in PATH."
fi
